name: CI/CD Workflow

on:
  push:
    branches: [ "main", "develop", "chore/#4-cicd" ]

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'corretto'

        - name: Gradle Caching
          uses: actions/cache@v4
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew clean build -x test

        - name: Create secrets files from GitHub Secrets
          run: |
            mkdir -p ./src/main/resources/secret
            echo "${{ secrets.PROD_ENV_CONTENT }}" > ./src/main/resources/secret/prod.env
            echo "${{ secrets.DEV_ENV_CONTENT }}" > ./src/main/resources/secret/dev.env
            cat <<'EOF' > ./src/main/resources/secret/deploy.sh
            ${{ secrets.DEPLOY_FILE }}
            EOF
            chmod 600 ./src/main/resources/secret/*.env
            chmod 600 ./src/main/resources/secret/deploy.sh
            echo "✅ .env & .sh 파일 생성 완료"
        
        - name: Docker Login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Copy deployment files to NCP server (Integrated SCP)
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            target: /root
            source: >
              src/main/resources/secret/prod.env
              src/main/resources/secret/dev.env
              src/main/resources/secret/deploy.sh
              docker-compose.yml

        # ---------------------- PROD Deployment ----------------------
        - name: Docker build & push (prod)
          if: github.ref == 'refs/heads/main'
          run: |
            SHA=${{ github.sha }}
            SHORT_SHA=${SHA:0:7}
            IMAGE_NAME=${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE_NAME }}
            
            echo "✅ Building $IMAGE_NAME with tags $SHORT_SHA and prod"
            
            docker build -f Dockerfile -t $IMAGE_NAME:$SHORT_SHA .
            docker tag $IMAGE_NAME:$SHORT_SHA $IMAGE_NAME:prod
            
            docker push $IMAGE_NAME:$SHORT_SHA
            docker push $IMAGE_NAME:prod
            
            echo "✅ Pushed $IMAGE_NAME:$SHORT_SHA and $IMAGE_NAME:prod"

        - name: Deploy to prod
          if: github.ref == 'refs/heads/main'
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              echo "🚀 Deploying to PROD server..."
              
              cd /root
              chmod +x deploy.sh
              ./deploy.sh prod

        # ---------------------- DEV Deployment ----------------------
        - name: Docker build & push (develop)
          if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/chore/#4-cicd'
          run: |
            IMAGE_NAME=${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE_NAME }}
            
            echo "✅ Building $IMAGE_NAME with tags dev"
            
            docker build -f Dockerfile -t $IMAGE_NAME:dev .
            docker push $IMAGE_NAME:dev
            
            echo "✅ Pushed $IMAGE_NAME:dev"

        - name: Deploy to develop
          if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/chore/#4-cicd'
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              echo "🚀 Deploying to DEV server..."
              
              cd /root
              chmod +x deploy.sh
              ./deploy.sh dev